version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.12 #
      environment:
        GO111MODULE: "on"
    working_directory: /go/src/github.com/bgpat/gomplete
    steps:
    - checkout
    - restore_cache:
        keys:
        - go-mod-v1-{{ checksum "go.sum" }}
    - run: go mod vendor
    - save_cache:
        key: go-mod-v1-{{ checksum "go.sum" }}
        paths:
        - "/go/src/github.com/bgpat/gomplete/vendor"
    - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    - run: bash <(curl -s https://codecov.io/bash)
    - run: go test -v -race ./_test/e2e/...
